# Generated by Django 4.2.10 on 2024-02-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="request",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
